/**
 * Passphrase wordlist.
 *
 * Curated for typing: common English words, 3-8 letters, no homophones that
 * are hard to spell from memory, no profanity, no plurals of other entries.
 * The list is deduplicated and frozen at load time; `WORDLIST.length` feeds
 * the entropy estimate directly, so adding or removing words is safe.
 */

const WORDS = `
able about above absorb accent accept access acorn acre across action active actor adapt add admire adobe adopt adult advance affair afford afraid after again agent agree ahead aim air aisle alarm album alert alien alike alive alley allow almond almost alone along aloud alpha also alter always amaze amber amber amount ample amuse anchor ancient anger angle animal ankle annual answer antenna antique anvil anxious any apart apex apple apply april apron arcade arch arctic area arena argue arise armor army aroma around arrange arrive arrow art artist ask aspect asset assist assume asthma astro atlas atom attach attack attend attic auburn audio august aunt author auto autumn avenue avoid awake award aware away awesome awful axis
baby bacon badge bagel baker balance balcony bald ballot bamboo banana band banjo banker banner barbecue bare barge barley barn barrel basalt basic basil basin basket bat batch bath baton battery bay beach beacon beam bean bear beat beaver become bedrock beef beehive beetle before began begin behave behind being believe bell belong below belt bench bend beneath benefit berry beside best better between beyond bicycle bidder big bike billion binary bind biology birch bird birth biscuit bishop bison bit bitter black blade blame blank blanket blast blaze bleach blend bless blind blink block blond blood bloom blossom blouse blue bluff blunt blur board boast boat bobcat body boil bold bolt bond bone bonus book boost booth border born borrow boss both bottle bottom bounce bound bow bowl box boy brace bracket braid brain brake branch brand brass brave bread break breeze brick bridge brief bright bring brisk broad broken bronze brook broom brother brown brush bubble bucket budget buffalo build bulb bulk bull bundle bunker burden burger burn burrow burst bus bush business busy butter button buy buzz
cabin cable cactus cage cake calm camel camera camp canal cancel candle candy cannon canoe canvas canyon cap capital captain car carbon card cargo carpet carrot carry cart carve case cash casino castle casual cat catalog catch cattle cause caution cave cedar ceiling celery cell cement census center century ceramic cereal certain chain chair chalk champion chance change channel chapter charge charm chart chase cheap check cheese chef cherry chess chest chew chicken chief child chili chill chimney chip choice choose chorus chosen chrome chunk cider cigar cinema circle circus citizen city civic civil claim clam clamp clap clarify clash class classic clause claw clay clean clear clerk clever click client cliff climb clinic clip cloak clock close cloth cloud clover club clue cluster clutch coach coal coast coat cobalt cobra cocoa code coffee coil coin cold collar collect colony color column comb combine come comedy comet comfort comic command comment common compact company compare compass compete complex concert concrete condor conduct cone confirm connect consent consider console constant contact contain content contest context control convert cook cool copper copy coral cord core cork corn corner correct cost cottage cotton couch cougar could council count country couple courage course court cousin cover cow coyote cozy crab crack cradle craft crane crash crate crawl crayon cream create credit creek crest crew cricket crimson crisp critic crop cross crowd crown crucial cruise crumb crush crust cry crystal cube cuckoo cucumber cuff culture cup curious curl current curtain curve cushion custom cut cycle cypress
dagger daily dairy daisy damage damp dance danger dare dark dart dash data date dawn day deal dean dear debate debris decade decent decide deck declare decor decrease deep deer defend define degree delay deliver delta demand denim dense dentist deny depart depend deposit depth deputy derby desert design desk detail detect develop device devote diagram dial diamond diary dice diesel diet differ digest digital dignity dinner dinosaur direct dirt disagree disc discuss disease dish dismiss display distance ditch dive divide dizzy doctor document dodge dog dollar dolphin domain dome donate donkey donor door dose dot double dough dove down dozen draft dragon drain drama draw dream dress drift drill drink drive drop drum dry duck due duet dune dungeon during dusk dust duty dwarf dwell dynamic
each eager eagle early earn earth easel east easy echo eclipse ecology economy edge edit educate effect effort egg eight either elbow elder electric elegant element elephant elevator elite else email embark embrace emerald emerge emotion employ empty enable enact enchant end endless endure enemy energy engage engine english enhance enjoy enlist enough enrich ensure enter entire entry envelope equal equip era erase errand error escape essay essence estate estimate eternal ethics evening event ever every evidence evolve exact example exceed excess exchange excite excuse execute exempt exercise exhale exhibit exist exit exotic expand expect expert expire explain explore export expose express extend extra extreme eye
fabric face fact factor fade fair faith falcon fall false fame family famous fan fancy fantasy far fare farm fashion fast fat fatal father fatigue fault favor feast feather feature february fee feed feel fellow female fence fern festival fetch fever few fiber fiction field fierce fifteen fifty fig figure file fill film filter final finance find fine finger finish fire firm first fiscal fish fist fit five fix flag flame flash flat flavor flee fleet flesh flex flight flip float flock flood floor flour flow flower fluid flute fly foam focus fog foil fold folk follow font food fool foot force forest forget fork form former fortune forum forward fossil foster found four fox fragile frame free freeze fresh friday fridge friend fringe frog front frost frown frozen fruit fuel full fun function fund funny fur furnace furry future fuzzy
gadget gain galaxy gallery game gap garage garden garlic garment gas gate gather gauge gaze gear gecko gem general genius gentle genuine gesture ghost giant gift giggle ginger giraffe girl give glacier glad glance glass glide glimpse globe gloom glory glove glow glue goal goat gold golf good goose gorilla gospel gossip govern gown grab grace grade grain grand granite grant grape graph grasp grass grateful gravel gravity gray great green greet grid grief grill grin grip grit grocery groove ground group grove grow guard guess guest guide guilt guitar gulf gull gum gun gutter guy gym
habit hair half hall halt hammer hamster hand handle happy harbor hard hare harm harmony harsh harvest hat hatch have hawk hazard haze head health heart heat heaven heavy hedge heel height helmet help hen herb herd here hero hidden hide high hill hint hip hire history hit hive hobby hockey hold hole hollow holy home honest honey honor hood hoof hook hope horizon horn horse hospital host hotel hour house hover howl hub huge human humble humid humor hundred hunger hunt hurdle hurry hurt husband hut hybrid hydrogen
ice icon idea ideal identify idle ignore ill image imagine impact import impose improve impulse inch include income increase indeed index indicate indoor industry infant inform inhale initial inject injury ink inner innocent input inquiry insect inside insight inspire install instant instead insult intact intend interest into invest invite iron island issue item ivory ivy
jacket jaguar jail jam january jar jaw jazz jeans jelly jersey jewel job jog join joint joke journal journey joy judge juice july jump june jungle junior jury just justice
kayak keen keep kernel ketchup kettle key kick kid kidney kind king kiosk kiss kit kitchen kite kitten knee kneel knife knight knit knob knock knot know koala
lab label labor lace ladder lady lagoon lake lamb lamp land lane language lantern lap laptop large laser last late later laugh launch laundry lava law lawn lawyer layer lazy lead leaf league lean leap learn lease leash least leather leave lecture ledge left leg legacy legal legend lemon lend length lens leopard lesson letter lettuce level liberty library license lid life lift light like lilac lily limb lime limit line linen link lion lip liquid list listen liter little live lizard load loaf loan lobby lobster local lock locker log logic lonely long look loop loose lord lose loss lost lotus loud lounge love low loyal luck lumber lunar lunch lung luxury lyric
machine mad magic magnet maid mail main major make mammal manage mango manner mansion manual maple marble march margin marine mark market marry marsh martial marvel mask mason mass master match material math matrix matter mature maximum maybe mayor maze meadow meal mean measure meat medal media medical medium meet melody melon melt member memory mention menu mercy merge merit merry mesh message metal meteor method metro middle midnight might mild mile milk mill million mimic mind mine mineral minor mint minute mirror miss mission mist mix mobile model modern modest modify moist moment monday money monitor monkey monster month mood moon moral more morning mosaic most motel mother motion motor mountain mouse mouth move movie much mud muffin mule multiply muscle museum mushroom music must mutual mystery myth
nail name napkin narrow nation native nature navy near neat neck need needle neighbor neon nephew nerve nest net network neutral never new news next nice nickel niece night nimble nine noble node noise none noodle noon normal north nose note nothing notice novel november now nuclear number nurse nut nutmeg
oak oasis oat obey object oblige observe obtain obvious occupy occur ocean october odd offer office often oil okay old olive omega omit once one onion online only onto open opera opinion oppose option orange orbit orchard order ordinary organ origin ostrich other otter ounce our outdoor outer outfit outline output outside oval oven over owl own oxygen oyster ozone
pace pack pact paddle page pail pain paint pair palace pale palm panda panel panic pants paper parade parcel parent park parrot parsley part partner party pass past pasta patch path patient patio patrol pattern pause pave payment peace peach peak peanut pear pearl pebble pecan pedal peel pen pencil penguin people pepper perch perfect perform perhaps period permit person pet phase phone photo phrase physical piano pick picnic picture piece pigeon pile pilgrim pill pilot pin pine pink pint pioneer pipe pirate pistol pitch pizza place plain plan plane planet plank plant plasma plastic plate play plaza pleasant please pledge plenty plot plug plum plunge plus pocket poem poet point polar pole police policy polish polite pond pony pool poppy popular porch pork port portion portrait position possible post pot potato pottery pouch pound pour powder power praise prawn pray precise prefer premium prepare present press pretty prevent price pride primary prince print prior prism prison private prize problem proceed process produce profile profit program project promise prompt proof proper protect proud prove provide public pudding puddle pull pulse pump pumpkin punch pupil puppy pure purple purpose purse push put puzzle pyramid
quail quake qualify quality quantum quarter queen query quest question queue quick quiet quilt quit quiver quiz quote
rabbit raccoon race radar radio radish raft rail rain raise rally ramp ranch random range rank rapid rare rat rate rather ratio raven raw ray razor reach react read ready real reason rebel recall receive recent recipe record recover recycle red reduce reef refer reflect reform refuse regard region regret regular reject relate relax release relief rely remain remark remedy remind remote remove render renew rent repair repeat replace reply report request require rescue research reserve resist resolve resource respect respond rest result retain retire retreat return reveal review reward rhythm ribbon rice rich ride ridge rifle right rigid ring rinse riot ripe rise risk ritual river road roast robin robot robust rock rocket rodeo role roll roof room root rope rose rotate rough round route royal rubber ruby rug rule rumor run runway rural rush rust
sable sad saddle safe saffron sail salad salmon salon salt salute same sample sand satin satisfy sauce sausage save saw say scale scan scarf scatter scene scheme school science scissor scoop scope score scout scrap screen script scroll sculpt sea seal search season seat second secret section secure seed seek seem segment select self sell seminar senate send senior sense sentence series serious serve session settle seven severe shadow shaft shallow shame shape share shark sharp shed sheep sheet shelf shell shelter shield shift shine ship shirt shiver shock shoe shoot shop shore short shoulder shout shove show shower shrimp shrink shrug shuffle shut shy sibling sick side siege sight sign silent silk silly silver similar simple since sing sink sir siren sister site situate six size skate sketch ski skill skin skirt skull sky slab slam slate sled sleep sleeve slender slice slide slight slim slogan slope slot slow small smart smell smile smoke smooth snack snake snap sneak sniff snow soap soccer social sock soda sofa soft soil solar soldier solid solve some son song soon sorry sort soul sound soup source south space spare spark speak special speech speed spell spend sphere spice spider spike spin spirit split spoil sponge spoon sport spot spray spread spring sprint spruce spy square squeeze squid stable stack stadium staff stage stair stamp stand star start state statue stay steady steak steal steam steel steep stem step stereo stick still sting stir stitch stock stomach stone stool stop store storm story stove strange straw stream street stress strike string strip strong struggle student studio study stuff style subject submit subway success such sudden sugar suggest suit sulfur summer summit sun sunny super supply support suppose supreme sure surface surge surprise survey survive suspect sustain swallow swamp swan swap swarm sweater sweep sweet swell swift swim swing switch sword symbol syrup system
table tackle tactic tail tailor take tale talent talk tall tank tape target task taste tavern tax taxi tea teach team tear tech tell temple tempo tenant tender tennis tent term test text thank theme then theory there thermal these thick thin thing think third thirty this thorn those thread three thrive throat throne through throw thumb thunder ticket tidal tide tiger tight tile timber time tiny tip tired tissue title toast today toe together toilet token tomato tomorrow ton tone tongue tonight tool tooth top topic torch total touch tough tour toward tower town toy trace track trade traffic trail train trait transfer trap travel tray treat tree trend trial tribe trick trigger trim trip triumph trolley trophy tropic trouble truck true trumpet trunk trust truth try tube tuck tuesday tulip tumble tuna tune tunnel turkey turn turtle twelve twenty twice twin twist type typical
ultra umbrella unable uncle under uniform unify union unique unit unite universe unknown unless until unusual unveil update upgrade uphold upon upper upset urban urge usage use useful usual utility
vacant vacuum vague valid valley value valve van vanilla vapor variety various vast vault vector velvet vendor venture venue verb verdict verify verse version vertical very vessel veteran viable vibrant victory video view village vintage vinyl violet violin virtual virus visible vision visit visual vital vivid vocal voice void volcano volume vote voyage
wafer wage wagon waist wait wake walk wall walnut want war warm warn warrior wash wasp waste watch water wave wax way weak wealth weapon wear weasel weather weave wedding wednesday weed week weigh weird welcome weld well west wet whale wheat wheel when where which while whisper whistle white whole wide widget width wild will win wind window wine wing wink winner winter wire wisdom wise wish wit witness wizard wolf woman wonder wood wool word work world worm worry worth wrap wreck wrist write wrong
yard yarn yawn year yeast yellow yes yesterday yet yield yoga yogurt young youth
zebra zero zigzag zinc zipper zone zoom
`;

export const WORDLIST = Object.freeze([
  ...new Set(WORDS.trim().split(/\s+/).filter((w) => w.length >= 3))
]);
